spring.application.name=ImageDownloader
pixabay.api.key=42051868-a14351063345743c62057332f
pixabay.api.url=https://pixabay.com/api/
server.port=8080

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
